# Generated by Django 4.1 on 2023-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danielpuicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
