# Generated by Django 4.1 on 2023-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danielpuicon', '0002_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skill',
            field=models.TextField(blank=True, max_length=850, null=True),
        ),
    ]
